DROP DATABASE IF EXISTS `OpenStudy`;
CREATE DATABASE `OpenStudy`;

CREATE TABLE `User`(
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`email` VARCHAR(50) UNIQUE NOT NULL,
	`username` VARCHAR(50) NOT NULL,
	`password` VARCHAR(100) NOT NULL,
	`token` VARCHAR(50) UNIQUE NOT NULL
) ENGINE=InnoDB;

CREATE TABLE `Set`(
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(50) NOT NULL,
	`description` VARCHAR(100) NOT NULL,
	`user_id` INT UNSIGNED,
	CONSTRAINT fk_set_user
        FOREIGN KEY (`user_id`) REFERENCES `User`(id)
        ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB;


CREATE TABLE `Term`(
	`id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`original` VARCHAR(50) NOT NULL,
	`definition` VARCHAR(100) NOT NULL,
	`set_id` INT UNSIGNED,
	CONSTRAINT fk_term_set
        FOREIGN KEY (`set_id`) REFERENCES `Set`(id)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;